#!/bin/bash

if [[ $1 -gt $2 ]]; then
    max=$1
    min=$2
else
    max=$2
    min=$1
fi

sum=0
for (( i = $min; i <= $max; i++ )); do
    sum=$(( sum + i ))
done
echo "$sum"

# https://www.codewars.com/kata/55f2b110f61eb01779000053/
