#!/bin/bash

n=$1
d=$2

# create one big string with all the squares containing d
string=
for (( i = 0; i <= n; i++ )); do
    square=$(( i ** 2 ))
    if [[ "$square" =~ "$d" ]]; then
        string="$string$square"

    fi
done

# loop through each character in string
counter=0
for (( i = 0; i < ${#string}; i++ )); do
    char=${string:i:1}
    if (( char == d )); then
        counter=$(( counter + 1 ))
    fi
done
echo "$counter"

# https://www.codewars.com/kata/566fc12495810954b1000030/
