#!/bin/bash

a=$1
b=$2
c=$3

counter=0
max=0

function is_max() {
    arg=$1
    if [[ $arg -gt $max ]]; then
        max="$arg"
    fi
}

while [[ "$counter" -le 4 ]]; do
    case "$counter" in
        0)
            expr0=$(( a * (b + c) ))
            is_max "$expr0"
            ;;
        1)
            expr1=$(( a * b * c ))
            is_max "$expr1"
            ;;
        2)
            expr2=$(( a + b * c ))
            is_max "$expr2"
            ;;
        3)
            expr3=$(( (a + b) * c ))
            is_max "$expr3"
            ;;
        4)
            expr4=$(( a + b + c ))
            is_max "$expr4"
            ;;
    esac
    counter=$((counter + 1))
done

echo "$max"

# https://www.codewars.com/kata/5ae62fcf252e66d44d00008e/
