#!/bin/bash

# An Armstrong number is a number that is the sum of its own digits each 
# raised to the power of the number of digits.
# For example:
# 9 is an Armstrong number, because 9 = 9^1 = 9
# 10 is not an Armstrong number, because 10 != 1^2 + 0^2 = 1
# 153 is an Armstrong number, because: 153 = 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153
# 154 is not an Armstrong number, because: 154 != 1^3 + 5^3 + 4^3 = 1 + 125 + 64 = 190
# Write some code to determine whether a number is an Armstrong number.
# https://exercism.org/tracks/bash/exercises/armstrong-numbers

input="$1"

if [[ ! "$input" =~ ^[0-9]+$ ]]; then    # test if input is integer
    exit 1
fi

num_digits="${#input}"    # number of digits a.k.a. 'length' of string
sum=0
for (( i = 0; i < "$num_digits"; i++ )); do    # iterate through each digit in number
    digit="${input:i:1}"
    sum=$(( sum + ( digit ** num_digits ) ))
done

if [[ "$sum" -eq "$input" ]]; then    # verify if sum is equal to input number
    echo "true"
else
    echo "false"
fi
