#!/bin/bash

# Calculate the number of grains of wheat on a chessboard given that the number on each square doubles.
# There are 64 squares on a chessboard (where square 1 has one grain, square 2 has two grains, and so on).
# Write code that shows:
# how many grains were on a given square, and
# the total number of grains on the chessboard
# https://exercism.org/tracks/bash/exercises/grains/

input="$1"

calc_grains_square() {    # calculate number of grains on a given square
    echo "2 ^ ( $1 - 1 )" | bc
}

if [[ "$input" == 'total' ]]; then    # display total number of grains on chessboard
    sum=0
    for (( i = 1; i <= 64; i++ )); do
        grains_square=$( calc_grains_square "$i" )
        sum=$( echo "$sum" + "$grains_square" | bc )
    done
    echo "$sum"

elif [[ "$input" =~ ^[0-9]+$ && "$input" -ge 1 && "$input" -le 64 ]]; then    # test if input is integer between 1-64
    calc_grains_square "$input"    

else
    echo "Error: invalid input"
    exit 1
fi
