#!/bin/bash

# Calculate the Hamming Distance between two DNA strands.
# If we compare two strands of DNA and count the differences between them 
# we can see how many mistakes occurred. This is known as the "Hamming Distance".
# We read DNA using the letters C,A,G and T. Two strands might look like this:
# GAGCCTACTAACGGGAT
# CATCGTAATGACGGCCT
# ^ ^ ^  ^ ^    ^^
# They have 7 differences, and therefore the Hamming Distance is 7.
# The Hamming distance is only defined for sequences of equal length, 
# so an attempt to calculate it between sequences of different lengths should not work.
# https://exercism.org/tracks/bash/exercises/hamming

if [[ ${#@} -ne 2 ]]; then    # exit if number of arguments is not 2
    echo "Usage: hamming.sh <string1> <string2>"
    exit 1
fi

length1=${#1}    # string length of 1st parameter
length2=${#2}    # string length of 2nd parameter
if [[ "$length1" -ne "$length2" ]]; then    # exit if lengths differ
    echo "strands must be of equal length"
    exit 1
fi

counter=0
for (( i = 0; i < "$length1"; i++ )); do         # loop character by character
    if [[ "${1:$i:1}" != "${2:$i:1}" ]]; then    # increase counter if characters differ
        counter=$(( counter + 1 ))
    fi
done
echo "$counter"
