#!/bin/bash

# Given a year, report if it is a leap year.
# https://exercism.org/tracks/bash/exercises/leap

year=$1

if [[ ${#@} -ne 1 || ! "$year" =~ ^[0-9]+$ ]]; then    # if number of arguments is not 1 or if argument is not integer
    echo "Usage: leap.sh <year>"
    exit 1
fi

february=$(cal 2 "$year")    # display calendar for given year
last_week=$(echo "$february" | tail -n 2 | head -n 1)    # extract last week of February

if [[ "$last_week" =~ 29 ]]; then    # test if last week contains "29"
    echo "true"
else
    echo "false"
fi
