#!/bin/bash

# Two-fer or 2-fer is short for two for one. One for you and one for me.
# Given a name, return a string with the message: One for name, one for me.
# Where "name" is the given name.
# However, if the name is missing, return the string: One for you, one for me.
# https://exercism.org/tracks/bash/exercises/two-fer

name="$1"            # name is 1st argument
name=${name:=you}    # set name to default value if name is unset

echo "One for $name, one for me."
